// App.test.tsx
import React from "react";
import { render, screen } from "@testing-library/react";
import App from "../app/components/LoadingStyle1"; // Adjust the path based on your folder structure
import { Spin } from "antd";

describe("App Component", () => {
  it("should render the Spin component with large size", () => {
    render(<App />);

    // Verify if the Spin component is in the document
    const spinElement = screen.getByRole("progressbar"); // Ant Design Spin uses a progressbar role
    expect(spinElement).toBeInTheDocument();

    // Check if the Spin component has the large class applied (class is generated by Ant Design for large size)
    expect(spinElement).toHaveClass("ant-spin-lg");
  });
});
